---
apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
spec:
  volumes:
    - name: shared-logs
      emptyDir: {}
  containers:
    - name: app-container
      image: alpine
      command: [ "/bin/sh" ]
      args: [
        "-c",
        "while true; do date >> /var/log/app.txt; sleep 5; done"
      ]
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log

    - name: sidecar-container
      image: nginx:1.15
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-logs
          mountPath: /usr/share/nginx/html
